baseURL = "https://muhfajar.id"
languageCode = "en-us"
title = "Fajar"
theme = "basics-fork"

[params]
    author = "Muhamad Fajar"
    github = "muhfajar"
    twitter = "__muhfajar"
    source = "_src"
