---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
  - author
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: https://img.weeknd.dev/w=720_output=webp
use_front_matter_path: true
file_template: ":day:-:month:-:year:-:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
